// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB54XbOfywRZARJuf1nCjAUbdf-SX7ZSGg',
    appId: '1:258874167309:web:87c721582c9351354e4544',
    messagingSenderId: '258874167309',
    projectId: 'tium-676e0',
    authDomain: 'tium-676e0.firebaseapp.com',
    storageBucket: 'tium-676e0.firebasestorage.app',
    measurementId: 'G-Y7MH1YRS18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_o2uXWE94-7SglKHDgiMdKg6--rFHFeA',
    appId: '1:258874167309:android:bc9d2642f5d68bf64e4544',
    messagingSenderId: '258874167309',
    projectId: 'tium-676e0',
    storageBucket: 'tium-676e0.firebasestorage.app',
  );
}
